// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace AndoSystem {
	[Serializable]
	public class Condition {
		public enum Type {
			ResourceValue,
			ResourcePercentage,
			SkillValue,
			StatValue,
		}

		public string id;
		public float value;

		public bool Evaluate(Actor actor) {
			return true;
		}
	}
}