// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;

namespace AndoSystem {
	public class PowerDefinition {
		public string name {get; private set;}
		public string[] description {get; private set;}

		//Usage
		public PowerType type {get; private set;} //{Hidden, Passive, Sustained, Active}
		public PowerUsage usage {get; private set;} //{AtWill, Encounter, Daily, Once}

		//Targetting
		public TargetFilter filter {get; private set;} //{Allies, Enemies, Any, Empty}
		public TargetShape shape {get; private set;} //{Blast, Burst, Line}
		public int[] range {get; private set;}
		public int[] size {get; private set;}

		//Requirements
		public Condition[][] Prerequisites; //list of conditions for this power to be upgraded and used
		public Condition[][] Requirements; //list of conditions for this power to be used

		//Functionality
		public Action<Actor> Attach; //called when power is added to actor
		public Action<Actor> Detach; //called when power is removed from actor
		public Func<Actor, TargetData, int, IEnumerator> Effect; //coroutine for the effect of a power
	}
}