// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AndoSystem {
	public enum PowerType {
		Hidden,
		Passive,
		Sustained,
		Active
	}

	public enum PowerUsage {
		AtWill,
		Encounter,
		Daily,
		Once
	}

	public enum TargetFilter {
		Allies,
		Enemies,
		Any,
		Empty
	}

	public enum TargetShape {
		Blast,
		Burst,
		Line
	}
}

