// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AndoSystem {
	[Serializable]
	public class Resource {
		float _current;
		public float current {
			get {
				return _current;
			}
			set {
				_current = value;

				OnChanged.Invoke(_current);
				if (_current >= maximum)
					OnMaximum.Invoke();
				if (_current <= minimum)
					OnMinimum.Invoke();
			}
		}
		public float maximum;
		public float minimum;

		public event Action<float> OnChanged = delegate(float obj) {};
		public event Action OnMaximum = delegate {};
		public event Action OnMinimum = delegate {};
	}
}