// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections;

namespace AndoSystem {
	public class ResourceList : IEnumerable {
		Dictionary<string, Resource> _rdict = new Dictionary<string, Resource>();

		public bool HasResource(string name) {
			if (_rdict.ContainsKey(name)) return true;
			else return false;
		}

		public Resource GetResource(string name) {
			if (!_rdict.ContainsKey(name)) {
				_rdict.Add(name, new Resource());
			}
			return _rdict[name];
		}

		public IEnumerator GetEnumerator() {
			return _rdict.GetEnumerator();
		}

		public Resource this[string name] {
			get {
				return GetResource(name);
			}
		}
	}
}