// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using UnityEngine;

namespace AndoSystem {
	[DisallowMultipleComponent]
	[RequireComponent(typeof(HexTransform))]
	public class Actor : MonoBehaviour {
//		Initiative _initiative; //This actor can take part in combat turns
//		Movement _movement; //This actor can move
//		PowerList _powers; //This actor can use powers
		
//		public ResourceList resources {get; protected set;} //This actor has trackable temporary values
		//SkillList _skills; //This actor has trackable long-term values
		//ModifierList _modifiers; //This actor has modifiers which can be accessed

		//Inventory _inventory; //This actor can store other actors
		//Equipment _equipment; //This actor can equip other actors

		//Item _item; //This actor can be stored in another actor
		//Weapon _weapon; //This actor can be used as a weapon by another actor
		//Armor _armor; //This actor can be used as armor by another actor
		//Accessory _accessory; //This actor can be used as an accessory by another actor
		//Usable _usable; //This actor can be activated by other actors
	}
}