// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;
using System;

namespace AndoSystem {
	[DisallowMultipleComponent]
	public class HexTransform : MonoBehaviour {
		public HexTransform parent {
			get {return transform.parent.GetComponent<HexTransform>();}
			set {transform.parent = value.transform;}
		}

		public Hex localPosition {
			get {return Hex.FromVector(transform.localPosition);}
			set {transform.localPosition = Hex.ToVector(value);}
		}
		public Quaternion rotation {
			get {return transform.rotation;}
			set {transform.rotation = value;}
		}
		public Vector3 scale {
			get {return transform.lossyScale;}
			set {transform.lossyScale = value;}
		}
	}
}